# Generated by Django 5.1.7 on 2025-04-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorra',
            name='imagen',
            field=models.ImageField(upload_to='Tienda/gorras/'),
        ),
    ]
