# Generated by Django 5.1.7 on 2025-04-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_alter_gorra_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorra',
            name='imagen',
            field=models.ImageField(upload_to='gorras/'),
        ),
    ]
