# Generated by Django 5.1.7 on 2025-04-05 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_alter_gorra_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gorra',
            name='imagen',
        ),
        migrations.CreateModel(
            name='GorraImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='gorras/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('gorra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Tienda.gorra')),
            ],
            options={
                'verbose_name': 'Imagen de gorra',
                'verbose_name_plural': 'Imágenes de gorras',
                'ordering': ['orden'],
            },
        ),
    ]
