# Generated by Django 5.1.7 on 2025-04-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_remove_gorra_imagen_gorraimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorra',
            name='imagen',
            field=models.ImageField(default='', upload_to='gorras/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GorraImagen',
        ),
    ]
