# Generated by Django 5.1.7 on 2025-04-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0005_gorra_imagen_delete_gorraimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorra',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='gorras/'),
        ),
    ]
