# Generated by Django 5.1.7 on 2025-04-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0006_gorra_imagen2'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorra',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='gorras/'),
        ),
        migrations.AddField(
            model_name='gorra',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='gorras/'),
        ),
        migrations.AddField(
            model_name='gorra',
            name='imagen5',
            field=models.ImageField(blank=True, null=True, upload_to='gorras/'),
        ),
    ]
