# Generated by Django 5.1.7 on 2025-04-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0007_gorra_imagen3_gorra_imagen4_gorra_imagen5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='foto1',
            field=models.ImageField(default='pedidos/default.jpg', upload_to='pedidos/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='pedidos/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='pedidos/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='foto4',
            field=models.ImageField(blank=True, null=True, upload_to='pedidos/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='foto5',
            field=models.ImageField(blank=True, null=True, upload_to='pedidos/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
    ]
