# Generated by Django 5.1.7 on 2025-04-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0008_remove_pedido_cliente_remove_pedido_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
