# Generated by Django 4.0.1 on 2025-04-17 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0009_alter_pedido_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='gorra_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='Tienda.gorra'),
        ),
    ]
