# Generated by Django 5.2 on 2025-04-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0010_pedido_gorra_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='logo_original',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
