# Generated by Django 5.2 on 2025-06-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0011_pedido_logo_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='talla',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='visera',
            field=models.CharField(blank=True, choices=[('PLANA', 'Plana'), ('CURVA', 'Curva')], max_length=5, null=True),
        ),
    ]
